export const planos = [
  'DIAMANTE 270', 'RUBI 200', 'SAFIRA 300', 'DIAMANTE 260'
];

export const hospitais = [
  'HOSPITAL ISRAELITA SOC.BENEF.ISRAELITA DO RJ',
  'HOSPITAL SANTA CRUZ - SOC.PORT.DE BENEF.DE NITEROI',
  'HOSPITAL SAO PAULO - SPDM',
  'INETI-INST.DE TRAT. NEUROL. E DE TERAPIA INTENSIVA',
  'OBRA PORTUGUESA DE ASSISTENCIA',
  'PRONTOBABY LTDA - CLINICA INFANTIL DE URGENCIA',
  'TERAPIA INTENSIVA PEDIATRICA LTDA',
  'AMUR - ATENDIMENTO MEDICO DE URGENCIA',
  'UPB - URGENCIAS PEDIATRICAS BANGU',
  'ABBR - ASSOC.BRAS.BENEFICENTE DE REABILITACAO',
  'ASSOC. COMB. CANCER BRASIL CENTRAL -HOSP.H.ANGOTTI',
];