export const igr = [
{ nome:'DONA SAÚDE CLINICAS LTDA. ME (365645)', valor:'1', porte:'pequeno' } ,
{ nome:'PREVENT SENIOR CORPORATE OPERADORA DE SAÚDE LTDA. (413267) ', valor:'2', porte:'pequeno' } ,
{ nome:'BIOLIFE SAUDE OPERADORA DE PLANOS DE SAUDE LTDA (419311) ', valor:'3', porte:'pequeno' } ,
{ nome:'VIDA EMPRESARIAL OPERADORA DE PLANOS DE SAUDE LTDA (406210)', valor:'4', porte:'pequeno' } ,
{ nome:'FUNDAÇÃO IRMÃO DIAMANTINO (419044) ', valor:'5', porte:'pequeno' } ,
{ nome:'MEDGOLD ASSISTENCIA MEDICA LTDA - ME (419753)', valor:'6', porte:'pequeno' } ,
{ nome:'UNIMED FEDERAÇÃO INTERFEDERATIVA DAS COOPERATIVAS MÉDICAS DO CENTRO-OESTE E TOCANTINS (347361) ', valor:'7', porte:'pequeno' } ,
{ nome:'ORALCLASS ASSISTENCIA MÉDICA E ODONTOLOGICA LTDA. (402478) ', valor:'8', porte:'pequeno' } ,
{ nome:'ADVANCE PLANOS DE SAÚDE LTDA (335657)', valor:'9', porte:'pequeno' } ,
{ nome:'UNIX - SAÚDE LTDA (418137) ', valor:'10 ', porte:'pequeno' } ,
{ nome:'UNILIFE SAÚDE LTDA. (413402) ', valor:'1', porte:'médio' } ,
{ nome:'PAME - ASSOCIAÇÃO DE ASSISTÊNCIA PLENA EM SAÚDE (342408) ', valor:'2', porte:'médio' } ,
{ nome:'SAÚDE SIM LTDA (320111)', valor:'3', porte:'médio' } ,
{ nome:'CAIXA DE ASSISTÊNCIA À SAÚDE - CABERJ (324361) ', valor:'4', porte:'médio' } ,
{ nome:'SALUTAR SAÚDE SEGURADORA S/A (000027)', valor:'5', porte:'médio' } ,
{ nome:'TERRAMAR ADMINISTRADORA DE PLANO DE SAUDE LTDA (412759)', valor:'6', porte:'médio' } ,
{ nome:'CABERJ INTEGRAL SAÚDE S.A (415774) ', valor:'7', porte:'médio' } ,
{ nome:'UNIMED NOVA FRIBURGO-SOC.COOP.SERV.MED.HOSP.LTDA. (335479) ', valor:'8', porte:'médio' } ,
{ nome:'BIO SAÚDE SERVIÇOS MÉDICOS LTDA (402966) ', valor:'9', porte:'médio' } ,
{ nome:'UNIÃO MÉDICA - COOPERATIVA DE TRABALHO MÉDICO DE FEIRA DE SANTANA (414581) ', valor:'10 ', porte:'médio' } ,
{ nome:'UNIMED-RIO COOPERATIVA DE TRABALHO MEDICO DO RIO DE JANEIRO (393321) ', valor:'1', porte:'grande ' } ,
{ nome:'UNIMED NORTE/NORDESTE-FEDERAÇÃO INTERFEDERATIVA DAS SOCIEDADES COOPERATIVAS DE TRABALHO MÉDICO (324213)', valor:'2', porte:'grande ' } ,
{ nome:'PREVENT SENIOR PRIVATE OPERADORA DE SAÚDE LTDA (302147)', valor:'3', porte:'grande ' } ,
{ nome:'GEAP AUTOGESTÃO EM SAÚDE (323080)', valor:'4', porte:'grande ' } ,
{ nome:'BIOVIDA SAÚDE LTDA. (415111) ', valor:'5', porte:'grande ' } ,
{ nome:'CAIXA SEGURADORA ESPECIALIZADA EM SAÚDE S/A (418072) ', valor:'6', porte:'grande ' } ,
{ nome:'CAIXA DE ASSISTÊNCIA DOS FUNCIONÁRIOS DO BANCO DO BRASIL (346659)', valor:'7', porte:'grande ' } ,
{ nome:'UNIMED DO ESTADO DE SP - FEDERAÇÃO ESTADUAL DAS COOP. MÉDICAS (319996) ', valor:'8', porte:'grande ' } ,
{ nome:'GOLDEN CROSS ASSISTENCIA INTERNACIONAL DE SAÚDE LTDA (403911)', valor:'9', porte:'grande ' } ,
{ nome:'SUL AMERICA COMPANHIA DE SEGURO SAÚDE (006246) ', valor:'10 ', porte:'grande ' } ,
];

export const iap = [
{ nome:'VIDA EMPRESARIAL OPERADORA DE PLANOS DE SAUDE LTDA (406210)', valor:'1', porte:'pequeno' } ,
{ nome:'BIOLIFE SAUDE OPERADORA DE PLANOS DE SAUDE LTDA (419311) ', valor:'2', porte:'pequeno' } ,
{ nome:'DONA SAÚDE CLINICAS LTDA. ME (365645)', valor:'3', porte:'pequeno' } ,
{ nome:'MEDGOLD ASSISTENCIA MEDICA LTDA - ME (419753)', valor:'4', porte:'pequeno' } ,
{ nome:'ORALCLASS ASSISTENCIA MÉDICA E ODONTOLOGICA LTDA. (402478) ', valor:'5', porte:'pequeno' } ,
{ nome:'FUNDAÇÃO IRMÃO DIAMANTINO (419044) ', valor:'6', porte:'pequeno' } ,
{ nome:'GREEN LIFE SAÚDE ASSISTÊNCIA MÉDICA LTDA. (410471) ', valor:'7', porte:'pequeno' } ,
{ nome:'SOCIEDADE ESPANHOLA DE BENEFICENCIA (306207) ', valor:'8', porte:'pequeno' } ,
{ nome:'SAÚDE QUALITY LTDA. (367729) ', valor:'9', porte:'pequeno' } ,
{ nome:'PRONTOMED ASSISTÊNCIA MEDICA LTDA. (403849)', valor:'10 ', porte:'pequeno' } ,
{ nome:'UNILIFE SAÚDE LTDA. (413402) ', valor:'1', porte:'médio' } ,
{ nome:'SAÚDE SIM LTDA (320111)', valor:'2', porte:'médio' } ,
{ nome:'CABERJ INTEGRAL SAÚDE S.A (415774) ', valor:'3', porte:'médio' } ,
{ nome:'UNIHOSP SAÚDE S.A. (385255)', valor:'4', porte:'médio' } ,
{ nome:'PAME - ASSOCIAÇÃO DE ASSISTÊNCIA PLENA EM SAÚDE (342408) ', valor:'5', porte:'médio' } ,
{ nome:'SMEDSJ - SERVIÇOS MÉDICOS SÃO JOSE LTDA (349755) ', valor:'6', porte:'médio' } ,
{ nome:'ECOLE SERVIÇOS MÉDICOS LTDA (414298) ', valor:'7', porte:'médio' } ,
{ nome:'UNIMED RIO BRANCO COOPERATIVA DE TRABALHO MEDICO LTDA (337871) ', valor:'8', porte:'médio' } ,
{ nome:'UNIMED GOVERNADOR VALADARES COOP. DE TRABALHO MÉDICO LTDA. (386588)', valor:'9', porte:'médio' } ,
{ nome:'CAIXA DE ASSISTÊNCIA À SAÚDE - CABERJ (324361) ', valor:'10 ', porte:'médio' } ,
{ nome:'UNIMED NORTE/NORDESTE-FEDERAÇÃO INTERFEDERATIVA DAS SOCIEDADES COOPERATIVAS DE TRABALHO MÉDICO (324213)', valor:'1', porte:'grande ' } ,
{ nome:'UNIMED-RIO COOPERATIVA DE TRABALHO MEDICO DO RIO DE JANEIRO (393321) ', valor:'2', porte:'grande ' } ,
{ nome:'UNIMED DIVINOPOLIS - COOPERATIVA DE TRABALHO MEDICO LTDA (319121)', valor:'3', porte:'grande ' } ,
{ nome:'CAIXA SEGURADORA ESPECIALIZADA EM SAÚDE S/A (418072) ', valor:'4', porte:'grande ' } ,
{ nome:'CARE PLUS MEDICINA ASSISTENCIAL LTDA. (379956) ', valor:'5', porte:'grande ' } ,
{ nome:'AGEMED SAÚDE S.A. (339601) ', valor:'6', porte:'grande ' } ,
{ nome:'UNIMED UBERLÂNDIA COOPERATIVA REGIONAL TRABALHO MÉDICO LTDA (384577) ', valor:'7', porte:'grande ' } ,
{ nome:'GEAP AUTOGESTÃO EM SAÚDE (323080)', valor:'8', porte:'grande ' } ,
{ nome:'SUL AMERICA COMPANHIA DE SEGURO SAÚDE (006246) ', valor:'9', porte:'grande ' } ,
{ nome:'UNIMED-SÃO GONÇALO - NITERÓI - SOC.COOP.SERV.MED E HOSP LTDA (343731)', valor:'10 ', porte:'grande ' } ,
];

export const pfa = [
{ nome:'FUNDAÇÃO IRMÃO DIAMANTINO (419044) ', valor:'1', porte:'pequeno' } ,
{ nome:'AMAZÔNIA PLANOS DE SAÚDE LTDA (419052) ', valor:'1', porte:'pequeno' } ,
{ nome:'IRMANDADE DA SANTA CASA DE MISERICÓRDIA DE SÃO ROQUE (401137)', valor:'1', porte:'pequeno' } ,
{ nome:'ASSOCIAÇÃO PORTUGUESA BENEFICENTE VASCO DA GAMA (346292) ', valor:'1', porte:'pequeno' } ,
{ nome:'HOSPITAL NOSSA SENHORA DAS GRAÇAS LTDA. (309401) ', valor:'1', porte:'pequeno' } ,
{ nome:'ASSOCIAÇÃO SANTA CASA SAÚDE DE SOROCABA (418854) ', valor:'1', porte:'pequeno' } ,
{ nome:'SANTA LUZIA ASSISTENCIA MEDICA S.A. (358509) ', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED DAS ESTÂNCIAS PAULISTAS - OPERADORA DE PLANOS DE SAÚDE SOCIEDADE COOPERATIVA (348066) ', valor:'1', porte:'pequeno' } ,
{ nome:'CENTRAL OPERADORA DE PLANOS DE SAÚDE NORTE-NORDESTE SOCIEDADE COOPERATIVA (417092) ', valor:'1', porte:'pequeno' } ,
{ nome:'TELOS - FUNDAÇÃO EMBRATEL DE SEGURIDADE SOCIAL (316849)', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED CABO FRIO COOPERATIVA TRABALHO MÉDICO LTDA. (323357)', valor:'1', porte:'pequeno' } ,
{ nome:'OPERADORA UNICENTRAL DE PLANOS DE SAÚDE LTDA. (318477) ', valor:'1', porte:'pequeno' } ,
{ nome:'AMERON - ASSISTÊNCIA MÉDICA RONDÔNIA S/A. (321338) ', valor:'1', porte:'pequeno' } ,
{ nome:'SAMOC S.A. - SOCIEDADE ASSISTENCIAL MÉDICA E ODONTO CIRÚRGICA (343676) ', valor:'1', porte:'pequeno' } ,
{ nome:'ITAUSEG SAÚDE S.A. (000884)', valor:'1', porte:'pequeno' } ,
{ nome:'CB SAÚDE ADMINISTRAÇÃO EM SAUDE SUPLEMENTAR LTDA (418676)', valor:'1', porte:'pequeno' } ,
{ nome:'GAMEC - GRUPO DE ASSISTÊNCIA MEDICA EMPRESARIAL DO CEARÁ LTDA. (347591)', valor:'1', porte:'pequeno' } ,
{ nome:'CENTRO MÉDICO FÁTIMA LTDA (408883) ', valor:'1', porte:'pequeno' } ,
{ nome:'SOCIAL-SOCIEDADE ASSISTENCIAL E CULTURAL (315630)', valor:'1', porte:'pequeno' } ,
{ nome:'MH VIDA - OPERADORA DE PLANOS DE SAÚDE LTDA. (412015)', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED CACERES COOPERATIVA DE TRABALHO MÉDICO  (350346)', valor:'1', porte:'pequeno' } ,
{ nome:'PETROBRAS DISTRIBUIDORA S.A. (354571)', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED DE SERTAOZINHO -  COOPERATIVA DE TRABALHO MÉDICO (344150) ', valor:'1', porte:'pequeno' } ,
{ nome:'IRMANDADE DA SANTA CASA DE MISERICORDIA DE VITORIA (378038)', valor:'1', porte:'pequeno' } ,
{ nome:'GAMA SAUDE LTDA. (407011)', valor:'1', porte:'pequeno' } ,
{ nome:'OPERADORA UNIESTE DE PLANOS DE SAÚDE LTDA (354511) ', valor:'1', porte:'pequeno' } ,
{ nome:'SÃO FRANCISCO ASSISTÊNCIA MÉDICA LTDA (403962) ', valor:'1', porte:'pequeno' } ,
{ nome:'CLIMESA CLÍNICA MÉDICA SANTANA LTDA (342955) ', valor:'1', porte:'pequeno' } ,
{ nome:'PLANO SAÚDE SÃO FRANCISCO LTDA. (358053) ', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED REGIONAL DE FLORIANO - COOPERATIVA DE TRABALHO MÉDICO (316458)', valor:'1', porte:'pequeno' } ,
{ nome:'INDUSTRIAS NUCLEARES DO BRASIL S/A - INB (329282)', valor:'1', porte:'pequeno' } ,
{ nome:'FUNDAÇÃO ELETROBRÁS DE SEGURIDADE SOCIAL - ELETROS (313904)', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED DO OESTE DA BAHIA COOPERATIVA DE TRABALHO MÉDICO (325082) ', valor:'1', porte:'pequeno' } ,
{ nome:'ALVORECER - ASSOCIAÇÃO DE SOCORROS MÚTUOS (344800) ', valor:'1', porte:'pequeno' } ,
{ nome:'MEDICAL RIO ASSISTÊNCIA MÉDICA LTDA (419320) ', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED ANGRA DOS REIS COOPERATIVA DE TRABALHO MEDICO (322547)', valor:'1', porte:'pequeno' } ,
{ nome:'CAIXA ASSISTENCIAL UNIVERSITARIA DO RIO DE JANEIRO (347825)', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED BOA VISTA COOPERATIVA DE TRABALHO MÉDICO (304158) ', valor:'1', porte:'pequeno' } ,
{ nome:'ASSOCIAÇÃO DOS FUNCIONÁRIOS PÚBLICOS DO ESPÍRITO SANTO (394271)', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED ALTO SÃO FRANCISCO COOPERATIVA DE TRABALHO MÉDICO (348261)', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED VALE DO CARANGOLA COOPERATIVA DE TRABALHO MEDICO LTDA (337561)', valor:'1', porte:'pequeno' } ,
{ nome:'IRMANDADE DA SANTA CASA DE MISERICORDIA DE VALINHOS (410365) ', valor:'1', porte:'pequeno' } ,
{ nome:'FUNDAÇÃO LIBERTAS DE SEGURIDADE SOCIAL (378216)', valor:'1', porte:'pequeno' } ,
{ nome:'HBC SAÚDE LTDA. (414352) ', valor:'1', porte:'pequeno' } ,
{ nome:'ATIVIA-COOPERATIVA DE SERVIÇOS MEDICOS E HOSPITALARES (320510) ', valor:'1', porte:'pequeno' } ,
{ nome:'FREE LIFE OPERADORA DE PLANOS DE SAÚDE LTDA (351091) ', valor:'1', porte:'pequeno' } ,
{ nome:'SANAMED - SAÚDE SANTO ANTONIO LTDA (384585)', valor:'1', porte:'pequeno' } ,
{ nome:'CAMBORIÚ SAÚDE LTDA. (360147)', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED AGRESTE MERIDIONAL - COOPERATIVA DE TRABALHO MEDICO LTDA (312649) ', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED MARQUES DE VALENÇA COOPERATIVA DE TRABALHO MÉDICO LTDA. (321087)', valor:'1', porte:'pequeno' } ,
{ nome:'ASSOCIAÇÃO ADVENTISTA NORTE BRASILEIRA DE PREVENÇÃO E ASSISTÊNCIA A SAÚDE (406554) ', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED DE CIANORTE - COOPERATIVA DE TRABALHO MEDICO  (354627)', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED ANDRADAS COOPERATIVA DE TRABALHO MÉDICO (352861)', valor:'1', porte:'pequeno' } ,
{ nome:'SAÚDE GOIÂNIA LTDA (401196)', valor:'1', porte:'pequeno' } ,
{ nome:'IRMANDADE DE MISERICORDIA DE PORTO FERREIRA (329355) ', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED RESENDE COOPERATIVA DE TRABALHO MÉDICO (330566) ', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED DE PINDAMONHANGABA - COOPERATIVA TRABALHO MEDICO (342343) ', valor:'1', porte:'pequeno' } ,
{ nome:'ASSOCIAÇÃO POLICIAL DE ASSISTÊNCIA À SAÚDE - APAS SOROCABA/VOTORANTIM (410128) ', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED SUDOESTE DE MINAS COOPERATIVA DE TRABALHO MÉDICO (324175) ', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED DE SOBRAL COOPERATIVA DE TRABALHO MÉDICO LTDA (303178)', valor:'1', porte:'pequeno' } ,
{ nome:'POLI SAUDE OPERADORA DE PLANO DE SAUDE LTDA (351270) ', valor:'1', porte:'pequeno' } ,
{ nome:'IRMANDADE DA SANTA CASA DE MISERICORDIA DE LIMEIRA (319422)', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED DE LINS - COOPERATIVA DE TRABALHOS MÉDICOS (354279) ', valor:'1', porte:'pequeno' } ,
{ nome:'SAMIG - SERV. DE ASSISTENCIA MEDICA DA ILHA DO GOVERNADOR LTDA (340162)', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED FRANCISCO BELTRAO COOPERATIVA DE TRABALHO MEDICO (336858) ', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED METROPOLITANA DO AGRESTE - COOPERATIVA DE TRABALHO MÉDICO (318566)', valor:'1', porte:'pequeno' } ,
{ nome:'ASSOCIAÇÃO MAIS SAÚDE SANTA CASA DE SÃO JOÃO DA BOA VISTA (419150) ', valor:'1', porte:'pequeno' } ,
{ nome:'FUNDAÇÃO PADRE ALBINO (413399) ', valor:'1', porte:'pequeno' } ,
{ nome:'AME-ASSISTÊNCIA MÉDICA A EMPRESAS LTDA (304531)', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED APUCARANA COOPERATIVA DE TRABALHO MÉDICO (358096) ', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED DE VOTUPORANGA - COOPERATIVA DE TRABALHO MÉDICO (328073)', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED INCONFIDENTES COOPERATIVA DE TRABALHO MÉDICO LTDA. (304395) ', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED PATROCÍNIO COOPERATIVA DE TRABALHO MÉDICO LTDA. (355593)', valor:'1', porte:'pequeno' } ,
{ nome:'CAIXA DE ASSISTÊNCIA DOS EMPREGADOS DO SISTEMA FINANCEIRO BANESTES (343331)', valor:'1', porte:'pequeno' } ,
{ nome:'ELOSAÚDE - ASSOCIAÇÃO DE ASSISTÊNCIA À SAÚDE (417297)', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED ALTO DA SERRA - SOCIEDADE COOPERATIVA DE SERVIÇO MÉDICO LTDA. (343684)', valor:'1', porte:'pequeno' } ,
{ nome:'SANTA CASA DE MISERICÓRDIA DE VOTUPORANGA (330116) ', valor:'1', porte:'pequeno' } ,
{ nome:'PRONTOCLINICA E HOSPITAIS SAO LUCAS S/A (305626) ', valor:'1', porte:'pequeno' } ,
{ nome:'SISTEMA TOTAL DE SAÚDE LTDA. (402001)', valor:'1', porte:'pequeno' } ,
{ nome:'SINDIFISCO NACIONAL - SINDICATO NACIONAL DOS AUDITORES-FISCAIS DA RECEITA FEDERAL DO BRASIL (361011) ', valor:'1', porte:'pequeno' } ,
{ nome:'SAMEDIL SERVIÇOS DE ATENDIMENTO MÉDICO S/A (335614)', valor:'1', porte:'pequeno' } ,
{ nome:'OPERADORA DE PLANOS PRIVADOS DE ASSISTENCIA A SAUDE CONSAUDE S/S LTDA (350729) ', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED CENTRO SUL FLUMINENSE COOPERATIVA DE TRABALHO MÉDICO (320897) ', valor:'1', porte:'pequeno' } ,
{ nome:'CAIXA DE ASSISTÊNCIA À SAÚDE DOS EMPREGADOS DA CELG (361461) ', valor:'1', porte:'pequeno' } ,
{ nome:'CAIXA DE ASSISTÊNCIA DO SETOR ELÉTRICO - E-VIDA (418374) ', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED DE ITAPETININGA - COOPERATIVA DE TRABALHO MÉDICO (353027) ', valor:'1', porte:'pequeno' } ,
{ nome:'COOPERATIVA DE TRABALHO MÉDICO DO PLANALTO NORTE DE SANTA CATARINA LTDA (317012) ', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED TRÊS CORAÇÕES COOPERATIVA DE TRABALHO MÉDICO LTDA. (359033) ', valor:'1', porte:'pequeno' } ,
{ nome:'ASSOCIAÇÃO SANTA CASA SAÚDE DE ARAÇATUBA (418803)', valor:'1', porte:'pequeno' } ,
{ nome:'IRMANDADE DA SANTA CASA DE MISERICÓRDIA DE SÃO JOSÉ DO RIO PRETO (339539)', valor:'1', porte:'pequeno' } ,
{ nome:'ASSISTÊNCIA MÉDICO-HOSPITALAR LTDA. (415847) ', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED ITUIUTABA COOPERATIVA TRABALHO MÉDICO LTDA. (301060)', valor:'1', porte:'pequeno' } ,
{ nome:'UNIMED JOÃO MONLEVADE COOPERATIVA DE TRABALHO MÉDICO LTDA. (352314)', valor:'1', porte:'pequeno' } ,
{ nome:'PROMÉDICA - PROTEÇÃO MEDICA A EMPRESAS S.A. (326861) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED CARUARU-COOPERATIVA DE TRABALHO MEDICO (340952) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED MONTES CLAROS COOPERATIVA DE  TRABALHO MÉDICO LTDA. (304051)', valor:'1', porte:'médio' } ,
{ nome:'QUALLITY SAÚDE ASSISTÊNCIA MÉDICA AMBULATORIAL LTDA (418170) ', valor:'1', porte:'médio' } ,
{ nome:'SAMP MINAS ASSISTÊNCIA MÉDICA LTDA. (346471) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED SERGIPE - COOPERATIVA DE TRABALHO MÉDICO (337668) ', valor:'1', porte:'médio' } ,
{ nome:'IRMANDADE DA SANTA CASA DE MISERICÓRDIA DE MAUÁ (403920) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED FOZ DO IGUACU COOPERATIVA TRABALHO MEDICO (351792)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED RIO BRANCO COOPERATIVA DE TRABALHO MEDICO LTDA (337871) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED ARARUAMA COOPERATIVA DE TRABALHO MÉDICO LTDA (335215) ', valor:'1', porte:'médio' } ,
{ nome:'SANTO ANDRÉ PLANOS DE ASSISTENCIA MÉDICA LTDA. (400190)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DE CAMPOS COOPERATIVA DE TRABALHO MÉDICO (352683) ', valor:'1', porte:'médio' } ,
{ nome:'PROMED ASSISTÊNCIA MÉDICA LTDA (410632)', valor:'1', porte:'médio' } ,
{ nome:'JARDIM AMÉRICA SAÚDE LTDA. (414450)', valor:'1', porte:'médio' } ,
{ nome:'MED-TOUR ADMINISTRADORA DE BENEFÍCIOS E EMPREENDIMENTOS LTDA. (328537) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED TERESÓPOLIS COOPERATIVA DE TRABALHO MÉDICO (363774) ', valor:'1', porte:'médio' } ,
{ nome:'ASSOCIAÇÃO SANTA CASA SAÚDE DE SÃO JOSÉ DOS CAMPOS (419249)', valor:'1', porte:'médio' } ,
{ nome:'ASSOCIAÇÃO DE SAÚDE PORTUGUESA DE BENEFICÊNCIA (417530)', valor:'1', porte:'médio' } ,
{ nome:'PLENA SAÚDE LTDA (348830)', valor:'1', porte:'médio' } ,
{ nome:'SAMED - SERVIÇOS DE ASSISTÊNCIA MÉDICA, ODONTOLÓGICA E HOSPITALAR S.A. (309192)', valor:'1', porte:'médio' } ,
{ nome:'ALLIANZ SAÚDE S/A (000515) ', valor:'1', porte:'médio' } ,
{ nome:'ASSOCIAÇÃO BRASILEIRA DOS EMPREGADOS EM TELECOMUNICAÇÕES (338915)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DO SUDOESTE COOPERATIVA DE TRABALHO MEDICO LTDA (350371)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED RONDÔNIA - COOPERATIVA DE TRABALHO MÉDICO (337374)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED CAMPINA GRANDE - COOPERATIVA DE TRABALHO MEDICO LTDA (367397) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DO ABC - COOPERATIVA DE TRABALHO MÉDICO (345270)', valor:'1', porte:'médio' } ,
{ nome:'PASA - PLANO DE ASSISTENCIA A SAUDE DO APOSENTADO DA VALE (331988) ', valor:'1', porte:'médio' } ,
{ nome:'NOSSA SAÚDE - OPERADORA PLANOS PRIVADOS DE ASSISTÊNCIA  À SAÚDE LTDA. (372609) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED ANÁPOLIS COOPERATIVA DE TRABALHO MÉDICO. (312347) ', valor:'1', porte:'médio' } ,
{ nome:'ASSISTÊNCIA MÉDICA SÃO MIGUEL LTDA (325236)', valor:'1', porte:'médio' } ,
{ nome:'PORTOMED - PORTO SEGURO SERVIÇOS DE SAUDE LTDA (417491)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED IMPERATRIZ COOPERATIVA DE TRABALHO MÉDICO (352543)', valor:'1', porte:'médio' } ,
{ nome:'ECONOMUS INSTITUTO DE SEGURIDADE SOCIAL (342611) ', valor:'1', porte:'médio' } ,
{ nome:'CASA DE SAÚDE SÃO BERNARDO S/A (363766)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED LITORAL COOPERATIVA DE TRABALHO MÉDICO LTDA (303356)', valor:'1', porte:'médio' } ,
{ nome:'AMESC - ASSOCIAÇÃO MÉDICA ESPÍRITA CRISTÃ (401081) ', valor:'1', porte:'médio' } ,
{ nome:'POLICLIN SAÚDE S/A. (415693) ', valor:'1', porte:'médio' } ,
{ nome:'SERMED-SAÚDE LTDA. (303739)', valor:'1', porte:'médio' } ,
{ nome:'UNIHOSP - SERVIÇOS DE SAÚDE LTDA. (412538) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED PETROPOLIS COOPERATIVA DE TRABALHO MÉDICO (323993)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED ITABUNA COOPERATIVA DE TRABALHO MEDICO (357065) ', valor:'1', porte:'médio' } ,
{ nome:'ASSOCIAÇÃO DA SANTA CASA SAÚDE DE RIBEIRÃO PRETO (417947)', valor:'1', porte:'médio' } ,
{ nome:'PARANA ASSISTENCIA MEDICA LTDA (315265)', valor:'1', porte:'médio' } ,
{ nome:'SERVIÇO FEDERAL DE PROCESSAMENTO DE DADOS (SERPRO) (345474)', valor:'1', porte:'médio' } ,
{ nome:'SISTEMAS E PLANOS DE SAÚDE LTDA. (352586)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED JI PARANÁ COOPERATIVA DE TRABALHO MÉDICO (347507) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED SALTO/ITU -  COOPERATIVA MÉDICA (346276)', valor:'1', porte:'médio' } ,
{ nome:'SANTA RITA SAUDE S/A. (348180) ', valor:'1', porte:'médio' } ,
{ nome:'EMPRESA BRASILEIRA DE TELECOMUNICAÇÕES S.A (320587)', valor:'1', porte:'médio' } ,
{ nome:'CAIXA DE ASSISTÊNCIA  DOS EMPREGADOS DA EMPRESA  BRASILEIRA DE PESQUISA  AGROPECUÁRIA (416401) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED COSTA DO DESCOBRIMENTO COOPERATIVA DE TRABALHO MÉDICO (324345)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DE MARILIA COOPERATIVA DE TRABALHO MÉDICO (336106)', valor:'1', porte:'médio' } ,
{ nome:'FUNDAÇÃO SANEPAR DE ASSISTÊNCIA SOCIAL (338648)', valor:'1', porte:'médio' } ,
{ nome:'AMHPLA COOPERATIVA DE ASSISTENCIA MEDICA (333221)', valor:'1', porte:'médio' } ,
{ nome:'ASSOCIAÇÃO ASSISTENCIAL DE SAÚDE SUPLEMENTAR CRUZ AZUL SAÚDE (411752)', valor:'1', porte:'médio' } ,
{ nome:'SMV SERVIÇOS MÉDICOS LTDA (349194) ', valor:'1', porte:'médio' } ,
{ nome:'GOOD LIFE SAUDE LTDA (305995)', valor:'1', porte:'médio' } ,
{ nome:'PLANO HOSPITAL SAMARITANO LTDA (411256)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DE ARARAQUARA - COOP. DE TRAB. MÉDICO (364312)', valor:'1', porte:'médio' } ,
{ nome:'MAPFRE SAÚDE LTDA (418951) ', valor:'1', porte:'médio' } ,
{ nome:'FUNDAÇÃO SABESP DE SEGURIDADE SOCIAL - SABESPREV (336165)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED SUL DO PARA COOPERATIVA DE TRABALHO MÉDICO (366145) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED VALE DO SEPOTUBA - COOPERATIVA DE TRABALHO MÉDICO (314099)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DE ARACATUBA - COOPERATIVA DE TRABALHO MÉDICO (369411)', valor:'1', porte:'médio' } ,
{ nome:'CEMIG SAÚDE (417505) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED NORTE FLUMINENSE COOPERATIVA DE TRABALHO MEDICO (312592)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED TERESINA - COOPERATIVA DE TRABALHO MÉDICO (353353)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED VALE DO AÇO COOPERATIVA DE TRABALHO MÉDICO (359289) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DE PRESIDENTE PRUDENTE COOPERATIVA DE TRAB.MÉDICO (315796)', valor:'1', porte:'médio' } ,
{ nome:'ASSOCIAÇÃO DOS SERVIDORES MUNICIPAIS, ESTADUAIS E FEDERAIS DO RIO DE JANEIRO (309028)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED PELOTAS/RS - COOPERATIVA DE ASSISTÊNCIA À SAÚDE LTDA. (311375)', valor:'1', porte:'médio' } ,
{ nome:'FEDERAÇAO REGIONAL DAS COOPERATIVAS MÉDICAS UNIMEDS DOS ESTADOS DE GOIAS E TOCANTINS E DO DISTRITO FEDERAL (386596)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DE PARANAGUÁ COOPERATIVA DE TRABALHO MÉDICO (361615)', valor:'1', porte:'médio' } ,
{ nome:'FUNDAÇÃO CESP (315478) ', valor:'1', porte:'médio' } ,
{ nome:'FUNDAÇÃO CELESC DE SEGURIDADE SOCIAL - CELOS (315044)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED RONDONOPOLIS COOPERATIVA DE TRABALHO MÉDICO LTDA (359777) ', valor:'1', porte:'médio' } ,
{ nome:'AUSTACLINICAS ASSISTÊNCIA MÉDICA E HOSPITALAR LTDA (327417)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED SOROCABA COOPERATIVA DE TRABALHO MÉDICO (348295)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED FRANCA - SOCIEDADE COOPERATIVA DE SERVIÇOS MÉDICOS E HOSPITALARES (354783)', valor:'1', porte:'médio' } ,
{ nome:'CAIXA DE ASSISTENCIA A SAUDE DA UNIVERSIDADE (316873)', valor:'1', porte:'médio' } ,
{ nome:'CAIXA DE ASSISTÊNCIA DOS FUNCIONÁRIOS DO BANCO DO NORDESTE DO BRASIL (385697)', valor:'1', porte:'médio' } ,
{ nome:'HOSPITAL REGIONAL DE FRANCA S/A (309338) ', valor:'1', porte:'médio' } ,
{ nome:'PORTO ALEGRE CLÍNICAS LTDA. (346870) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED PLANALTO MÉDIO- COOPERATIVA DE SERVIÇOS MÉDICOS LTDA (319384) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED SÃO CARLOS - COOPERATIVA DE TRABALHO MÉDICO (354031)', valor:'1', porte:'médio' } ,
{ nome:'FUNDAÇÃO COPEL DE PREVIDÊNCIA E ASSISTÊNCIA SOCIAL (355151)', valor:'1', porte:'médio' } ,
{ nome:'ASSOCIAÇÃO EVANGELICA BENEFICENTE DE LONDRINA (326755) ', valor:'1', porte:'médio' } ,
{ nome:'CIRCULO OPERARIO CAXIENSE (310247) ', valor:'1', porte:'médio' } ,
{ nome:'MEDIPLAN ASSISTENCIAL LTDA (368849)', valor:'1', porte:'médio' } ,
{ nome:'ASSISTENCIA MEDICO HOSPITALAR SAO LUCAS S/A (323811) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED VALE DO SÃO FRANCISCO COOPERATIVA DE TRABALHO MÉDICO (323268) ', valor:'1', porte:'médio' } ,
{ nome:'UNIÃO SAÚDE LTDA. (314609) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED SETE LAGOAS COOPERATIVA TRABALHO MÉDICO (349534)', valor:'1', porte:'médio' } ,
{ nome:'MEDPLAN ASSISTÊNCIA MEDICA LTDA. (337510)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED VALE DO CAÍ/RS - COOPERATIVA DE ASSISTÊNCIA À SAÚDE LTDA. (313211)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED POÇOS DE CALDAS - SOC. COOP. DE TRAB. E SERVIÇOS MÉDICOS (316148) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DE TUBARAO - COOPERATIVA DE TRABALHO MEDICO DA REGIAO DA AMUREL (364860)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DE SANTA BÁRBARA D\'OESTE E AMERICANA - COOP DE TRABALHO MÉDICO (369292) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED AMPARO COOPERATIVA DE TRABALHO MÉDICO (345598)', valor:'1', porte:'médio' } ,
{ nome:'PRONTOMED PLANOS DE SAÚDE LTDA (301728)', valor:'1', porte:'médio' } ,
{ nome:'IRMANDADE DA SANTA CASA DE MISERICÓRDIA DE PIRACICABA (354562) ', valor:'1', porte:'médio' } ,
{ nome:'RN METROPOLITAN LTDA (414131)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED LITORAL SUL/RS - COOPERATIVA MÉDICA LTDA. (300136)', valor:'1', porte:'médio' } ,
{ nome:'SAÚDE SANTA TEREZA LTDA. (414930)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED NORDESTE PAULISTA - FED. INTRAFEDERATIVA DAS COOP. MÉDICAS (328294) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DE BARRETOS COOPERATIVA DE TRABALHO MÉDICO (347108) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED/RS FEDERAÇÃO DAS COOPERATIVAS MÉDICAS DO RS LTDA (367087) ', valor:'1', porte:'médio' } ,
{ nome:'BENEFICENCIA CAMILIANA DO SUL (318299) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DE DOURADOS COOPERATIVA DE TRABALHO MÉDICO LTDA (333662)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DE ARARAS COOPERATIVA DE TRABALHO MÉDICO (348082) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED SUL CAPIXABA COOPERATIVA DE TRABALHO MÉDICO (320706)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DE PARANAVAÍ COOPERATIVA DE TRABALHO MÉDICO (320862)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED FRONTEIRA NOROESTE/RS - COOPERATIVA DE ASSISTÊNCIA À SAÚDE LTDA. (352179) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED LAVRAS COOPERATIVA DE TRABALHO MÉDICO (345458)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DE BEBEDOURO COOPERATIVA DE TRABALHO MÉDICO (331341)', valor:'1', porte:'médio' } ,
{ nome:'CENTRO HOSPITALAR ATIBAIA LTDA. (350699) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED EXTREMO SUL COOPERATIVA DE TRABALHO MÉDICO (346209) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED CONSELHEIRO LAFAIETE COOPERATIVA DE TRABALHO MÉDICO LTDA (345709) ', valor:'1', porte:'médio' } ,
{ nome:'AMHA SAUDE S/A (418587)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED REGIONAL DE CAMPO MOURÃO COOP TRAB MEDICO  (306100) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DE BARRA MANSA SOC. COOP. SERV.MED.E HOSPIT. (330264) ', valor:'1', porte:'médio' } ,
{ nome:'SANTA CASA DE MISERICÓRDIA DE JUIZ DE FORA (342807)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED BARBACENA - COOPERATIVA DE TRABALHO MÉDICO LTDA (309087)', valor:'1', porte:'médio' } ,
{ nome:'PRO SALUTE SERVIÇOS PARA A SAÚDE LTDA. (369373)', valor:'1', porte:'médio' } ,
{ nome:'HUMANA ASSISTENCIA MEDICA LTDA (357511)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED SÃO LOURENÇO COOPERATIVA DE TRABALHO MÉDICO (370088)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED NOROESTE/RS - SOCIEDADE COOPERATIVA DE ASSISTÊNCIA À SAÚDE LTDA. (357260) ', valor:'1', porte:'médio' } ,
{ nome:'ASSOCIAÇÃO DR. BARTHOLOMEU TACCHINI (342556) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DE OURINHOS - COOPERATIVA DE TRABALHO MÉDICO (311294) ', valor:'1', porte:'médio' } ,
{ nome:'PREMIUM SAÚDE EIRELI (417823)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED REGIONAL SUL GOIAS COOP. DE TRABALHO MÉDICO LTDA (305472) ', valor:'1', porte:'médio' } ,
{ nome:'METRUS INSTITUTO DE SEGURIDADE SOCIAL (380661) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED CURVELO COOPERATIVA DE TRABALHO MÉDICO LTDA. (330108) ', valor:'1', porte:'médio' } ,
{ nome:'LIFE EMPRESARIAL SAÚDE LTDA. (414492)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DE RIO CLARO SP COOPERATIVA DE TRABALHO MEDICO (306126) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED DE SÃO ROQUE - COOPERATIVA DE TRABALHO MÉDICO (318388)', valor:'1', porte:'médio' } ,
{ nome:'FUNDACAO LEONOR DE BARROS CAMARGO (410292) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED SANTA MARIA/RS - COOPERATIVA DE ASSISTÊNCIA À SAÚDE LTDA (319708) ', valor:'1', porte:'médio' } ,
{ nome:'SERPRAM-SERV.DE PREST.DE ASSISTÊNCIA MEDICO-HOSPITALAR S/A (306649)', valor:'1', porte:'médio' } ,
{ nome:'UNIMED COSTA OESTE - COOPERATIVA DE TRABALHO MÉDICO (371106) ', valor:'1', porte:'médio' } ,
{ nome:'UNIMED PONTA GROSSA COOPERATIVA DE TRABALHO MEDICO (349712)', valor:'1', porte:'médio' } ,
{ nome:'ASSOCIAÇAO DOS FUNCIONARIOS PUBLICOS DO ESTADO DO RIO GRANDE DO SUL (417599) ', valor:'1', porte:'médio' } ,
{ nome:'ASSOCIAÇÃO DE ASSISTÊNCIA À SAÚDE DOS EMPREGADOS DA COPASA (416568)', valor:'1', porte:'médio' } ,
{ nome:'MEDICAL MEDICINA COOPERATIVA ASSISTENCIAL DE LIMEIRA (360767)', valor:'1', porte:'médio' } ,
{ nome:'ASSOCIAÇÃO DE BENEFICÊNCIA E FILANTROPIA SÃO CRISTOVÃO (314218)', valor:'1', porte:'grande ' } ,
{ nome:'UNIMED RECIFE COOPERATIVA DE TRABALHO MÉDICO (344885)', valor:'1', porte:'grande ' } ,
{ nome:'SOMPO SAÚDE SEGUROS S.A. (000477)', valor:'1', porte:'grande ' } ,
{ nome:'UNIMED SAO JOSE DOS CAMPOS - COOPERATIVA DE TRABALHO MEDICO (331872) ', valor:'1', porte:'grande ' } ,
{ nome:'MEMORIAL SAUDE LTDA (373010) ', valor:'1', porte:'grande ' } ,
{ nome:'UNIMED DE MANAUS COOP. DO TRABALHO MÉDICO LTDA (311961)', valor:'1', porte:'grande ' } ,
{ nome:'UNIMED SAO JOSÉ DO RIO PRETO - COOP. DE TRABALHO MÉDICO (335100) ', valor:'1', porte:'grande ' } ,
{ nome:'SAMP ESPÍRITO SANTO ASSISTÊNCIA MÉDICA LTDA. (342033)', valor:'1', porte:'grande ' } ,
{ nome:'UNIMED JUNDIAI - COOPERATIVA DE TRABALHO MÉDICO (303267) ', valor:'1', porte:'grande ' } ,
{ nome:'UNIMED JOAO PESSOA - COOPERATIVA DE TRABALHO MÉDICO (321044) ', valor:'1', porte:'grande ' } ,
{ nome:'PLANO DE SAÚDE ANA COSTA LTDA. (360244)', valor:'1', porte:'grande ' } ,
{ nome:'UNIMED JUIZ DE FORA COOPERATIVA DE TRABALHO MÉDICO LTDA (306886) ', valor:'1', porte:'grande ' } ,
{ nome:'UNIMED BLUMENAU - COOPERATIVA DE TRABALHO MEDICO (334561)', valor:'1', porte:'grande ' } ,
{ nome:'UNIMED DO ESTADO DE SANTA CATARINA FED. EST. DAS COOP. MÉD. (355691) ', valor:'1', porte:'grande ' } ,
{ nome:'UNIMED DE LONDRINA COOPERATIVA DE TRABALHO MÉDICO (343269) ', valor:'1', porte:'grande ' } ,
{ nome:'UNIMED DE PIRACICABA SOCIEDADE COOPERATIVA DE SERVIÇOS MÉDICOS (315729)', valor:'1', porte:'grande ' } ,
{ nome:'VALE S/A (345695)', valor:'1', porte:'grande ' } ,
];
